name: Set Output
description: An action to simplify setting outputs
runs:
  using: node12
  main: index.js
inputs:
  variables:
    description: The variables that you want to define, separated by a newline
    required: true
