name: Set Output
description: An action to simplify setting outputs
branding:
  icon: list
  color: white
runs:
  using: node12
  main: dist/index.js
inputs:
  variables:
    description: The variables that you want to define, separated by a newline
    required: true
