name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: npm
      - run: npm ci
      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: npm
      - run: npm ci
      - name: Test
        run: npm test
      - name: Upload Coverage
        run: npm run coverage:report
      - uses: ./
        id: output-step
        with:
          variables: |
            FOO=BAR
            HELLO=$(echo WORLD)
      - name: Check FOO
        run: |
          echo "FOO is '${{ steps.output-step.outputs.FOO }}'"
          exit 1
        if: ${{ steps.output-step.outputs.FOO != 'BAR' }}
      - name: Check HELLO
        run: |
          echo "HELLO is '${{ steps.output-step.outputs.HELLO }}'"
          exit 1
        if: ${{ steps.output-step.outputs.HELLO != 'WORLD' }}
